import type { VerticalConfig } from '../vertical-schema';

/**
 * Primary vertical: construction equipment rental, Stuttgart region.
 * Benchmark figures are real, sourced public rate cards (see
 * data/rate-card-references.json). They prove the market spread exists;
 * they say nothing about this system's performance.
 */
export const equipmentRentalStuttgart: VerticalConfig = {
  slug: 'equipment-rental-stuttgart',
  label: 'Equipment rental — Stuttgart region',
  currency: 'EUR',
  vatRate: 0.19,
  taxLabel: 'VAT 19%',
  demoRequestSummary:
    'One 12-meter electric scissor lift, five business days, delivered before 07:00 Monday',
  specFields: [
    {
      id: 'equipment_category',
      label: 'Equipment category',
      type: 'select',
      required: true,
      options: ['scissor_lift', 'boom_lift', 'telehandler', 'mini_excavator'],
    },
    {
      id: 'working_height_m',
      label: 'Working height',
      type: 'number',
      unit: 'm',
      required: true,
    },
    {
      id: 'power_type',
      label: 'Power type',
      type: 'select',
      required: true,
      options: ['electric', 'diesel', 'hybrid', 'any'],
    },
    {
      id: 'indoor_outdoor',
      label: 'Indoor or outdoor use',
      type: 'select',
      required: true,
      options: ['indoor', 'outdoor', 'both'],
    },
    {
      id: 'ground_conditions',
      label: 'Ground conditions',
      type: 'select',
      required: true,
      options: ['paved', 'concrete_slab', 'gravel', 'rough_terrain'],
    },
    {
      id: 'site_access',
      label: 'Site access constraints',
      type: 'text',
      required: false,
      hint: 'Gates, door widths, ramps, load limits',
    },
    {
      id: 'delivery_address',
      label: 'Delivery address',
      type: 'text',
      required: true,
    },
    {
      id: 'delivery_date',
      label: 'Delivery date',
      type: 'date',
      required: true,
    },
    {
      id: 'delivery_window',
      label: 'Delivery window',
      type: 'time_window',
      required: true,
      hint: 'e.g. before 07:00',
    },
    {
      id: 'pickup_date',
      label: 'Pickup date',
      type: 'date',
      required: true,
    },
    {
      id: 'pickup_window',
      label: 'Pickup window',
      type: 'time_window',
      required: false,
    },
    {
      id: 'duration_business_days',
      label: 'Rental duration',
      type: 'number',
      unit: 'business days',
      required: true,
    },
    {
      id: 'accessories',
      label: 'Accessories',
      type: 'multiselect',
      required: false,
      options: ['pipe_rack', 'board_carrier', 'non_marking_tires', 'extension_deck'],
    },
    {
      id: 'operator_required',
      label: 'Operator required',
      type: 'boolean',
      required: true,
    },
    {
      id: 'charging_or_fuel',
      label: 'Charging or fuel on site',
      type: 'select',
      required: true,
      options: ['230v_available', '400v_available', 'no_power_on_site', 'diesel_refuel_needed'],
    },
    {
      id: 'insurance_preference',
      label: 'Insurance preference',
      type: 'select',
      required: true,
      options: ['supplier_liability_reduction', 'own_insurance', 'undecided'],
    },
    {
      id: 'deposit_tolerance',
      label: 'Deposit tolerance',
      type: 'select',
      required: true,
      options: ['none', 'up_to_500', 'up_to_1000', 'any'],
    },
    {
      id: 'budget_net',
      label: 'Budget (net)',
      type: 'number',
      unit: 'EUR',
      required: false,
      hint: 'Only stored if you provide one. Only revealed if you authorize it.',
    },
    {
      id: 'company',
      label: 'Company',
      type: 'text',
      required: true,
    },
    {
      id: 'contact',
      label: 'Contact person',
      type: 'text',
      required: true,
    },
  ],
  levers: [
    {
      id: 'may_reveal_budget',
      label: 'Reveal budget',
      description: 'The agent may state your budget when it helps close a better rate.',
      defaultAuthorized: false,
    },
    {
      id: 'may_adjust_delivery_window',
      label: 'Adjust delivery window',
      description: 'The agent may accept a wider delivery window if compensated.',
      defaultAuthorized: false,
    },
    {
      id: 'may_extend_rental_period',
      label: 'Extend rental period',
      description: 'The agent may extend the rental to reach a better weekly tier.',
      defaultAuthorized: false,
    },
    {
      id: 'may_accept_equivalent_equipment',
      label: 'Accept equivalent equipment',
      description: 'The agent may accept a technically equivalent machine.',
      defaultAuthorized: false,
    },
    {
      id: 'may_offer_repeat_business',
      label: 'Offer repeat business',
      description: 'The agent may mention realistic future rental volume.',
      defaultAuthorized: false,
    },
    {
      id: 'may_accept_pickup_instead_of_delivery',
      label: 'Accept self-pickup',
      description: 'The agent may accept picking the machine up yourself.',
      defaultAuthorized: false,
    },
    {
      id: 'may_commit_immediately',
      label: 'Commit immediately',
      description: 'The agent may commit to a booking up to your maximum commitment.',
      defaultAuthorized: false,
    },
  ],
  quoteCategories: [
    { id: 'rental', label: 'Rental rate', typicallyMandatory: true },
    { id: 'delivery', label: 'Delivery', typicallyMandatory: true },
    { id: 'pickup', label: 'Pickup', typicallyMandatory: true },
    { id: 'insurance', label: 'Liability reduction', typicallyMandatory: true },
    { id: 'accessory', label: 'Accessories', typicallyMandatory: false },
    { id: 'surcharge', label: 'Surcharges', typicallyMandatory: true },
    { id: 'discount', label: 'Discounts', typicallyMandatory: false },
    { id: 'deposit', label: 'Deposit (refundable)', typicallyMandatory: false },
    { id: 'cleaning', label: 'Cleaning (conditional)', typicallyMandatory: false },
    { id: 'fuel', label: 'Charging / fuel (conditional)', typicallyMandatory: false },
    { id: 'late_fee', label: 'Late return (conditional)', typicallyMandatory: false },
    { id: 'damage_waiver', label: 'Damage (conditional)', typicallyMandatory: false },
    { id: 'overtime', label: 'Overtime (conditional)', typicallyMandatory: false },
    { id: 'other', label: 'Other', typicallyMandatory: false },
  ],
  benchmark: {
    unit: 'EUR/day net, 12 m scissor lift, Germany',
    medianDailyRateNet: 99.0,
    references: [
      {
        source: 'GERKEN Arbeitsbühnen',
        url: 'https://gerken-arbeitsbuehnen.de/produkt/scheren-arbeitsbuehne-12m-w/gs-120-12-w',
        item: 'Scissor lift 11.95 m working height',
        daily_rate_net: 119.0,
        notes: 'Day rate excl. VAT; second 12 m model at 125.00 EUR/day',
        retrieved_at: '2026-07-18T21:35:00Z',
      },
      {
        source: 'BIBERGER',
        url: 'https://biberger.de/products/sb-120-d',
        item: 'SB 120-D diesel scissor lift, ~12 m',
        daily_rate_net: 93.0,
        notes: 'Plus 10% machine breakage insurance, transport, 18.60 EUR return fee',
        retrieved_at: '2026-07-18T21:35:00Z',
      },
      {
        source: 'BIBERGER',
        url: 'https://biberger.de/products/sb-120b-e',
        item: 'SB 120b-E electric scissor lift, 11.75 m',
        daily_rate_net: 93.0,
        notes: 'Electric drive; same fee structure',
        retrieved_at: '2026-07-18T21:35:00Z',
      },
      {
        source: 'klickrent',
        url: 'https://www.klickrent.de/mieten/produkt/12m-scherenbuehnen-diesel',
        item: '12 m diesel scissor lifts',
        daily_rate_net: 88.0,
        notes: '5-day basis; cleaning 94 EUR/h if required; overtime 1/8 day rate per extra hour',
        retrieved_at: '2026-07-18T21:35:00Z',
      },
    ],
  },
  redFlagRules: {
    belowBenchmarkMedianFraction: 0.7,
  },
  interviewOutline: [
    'What equipment do you need, and what working height must it reach?',
    'Indoors, outdoors, or both? What are the ground conditions?',
    'Where is the site, and are there access constraints?',
    'When must it arrive, and in what window? When does it go back?',
    'Electric or diesel? Is charging or fuel available on site?',
    'Any accessories or an operator?',
    'Insurance preference and deposit tolerance?',
    'Company and contact for the rental agreement?',
    'Do you want to state a budget? It stays private unless you authorize revealing it.',
  ],
  supplierSearchTemplate: 'scissor lift rental {region} Arbeitsbühnen Vermietung',
};
